services:
  # =========================================
  # 1. OS TRABALHADORES (Workers)
  # =========================================
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    volumes:
      - ./API/keys:/app/keys
    deploy:
      replicas: 3
    networks:
      - vulnerai-net
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  website:
    image: nginx:alpine
    volumes:
      - ./VsCode:/usr/share/nginx/html:ro
    deploy:
      replicas: 2
    networks:
      - vulnerai-net

  assets:
    image: nginx:alpine
    volumes:
      - ./Resources:/usr/share/nginx/html:ro
    deploy:
      replicas: 2
    networks:
      - vulnerai-net

  # =========================================
  # 2. OS LOAD BALANCERS INTERNOS (Ativo/Passivo)
  # =========================================

  # --- API ---
  lb-api-primary:
    image: nginx:alpine
    volumes:
      - ./nginx/lb-api.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - vulnerai-net

  lb-api-backup:
    image: nginx:alpine
    volumes:
      - ./nginx/lb-api.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - vulnerai-net

  # --- WEBSITE ---
  lb-web-primary:
    image: nginx:alpine
    volumes:
      - ./nginx/lb-website.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - website
    networks:
      - vulnerai-net

  lb-web-backup:
    image: nginx:alpine
    volumes:
      - ./nginx/lb-website.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - website
    networks:
      - vulnerai-net

  # --- ASSETS ---
  lb-res-primary:
    image: nginx:alpine
    volumes:
      - ./nginx/lb-assets.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - assets
    networks:
      - vulnerai-net

  lb-res-backup:
    image: nginx:alpine
    volumes:
      - ./nginx/lb-assets.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - assets
    networks:
      - vulnerai-net

  # =========================================
  # 3. O INGRESS (Porteiro Principal)
  # =========================================
  ingress:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/ingress.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lb-api-primary
      - lb-api-backup
      - lb-web-primary
      - lb-web-backup
      - lb-res-primary
      - lb-res-backup
    networks:
      - vulnerai-net

networks:
  vulnerai-net:
    driver: bridge
