events { worker_connections 1024; }

http {
    # --- GRUPO API (Com Failover) ---
    upstream api_cluster_lb {
        # O Nginx tenta este primeiro
        server lb-api-primary:80;
        # Só usa este se o de cima falhar (timeout ou erro)
        server lb-api-backup:80 backup;
    }

    # --- GRUPO WEBSITE (Com Failover) ---
    upstream website_cluster_lb {
        server lb-web-primary:80;
        server lb-web-backup:80 backup;
    }

    # --- GRUPO ASSETS (Com Failover) ---
    upstream assets_cluster_lb {
        server lb-res-primary:80;
        server lb-res-backup:80 backup;
    }

    server {
        listen 80;

        # Rota API
        location ~ ^/(scan|scans|targets|health|presets)($|/|\?) {
            proxy_pass http://api_cluster_lb;
            proxy_set_header Host $host;
            # ... configurações de websocket ...
        }

        # Rota Assets
        location ~* ^/resources/ {
            rewrite ^/resources/(.*) /$1 break;
            rewrite ^/Resources/(.*) /$1 break;
            proxy_pass http://assets_cluster_lb;
        }

        # Rota Website
        location / {
            proxy_pass http://website_cluster_lb;
            proxy_set_header Host $host;
        }
    }
}