events { worker_connections 1024; }
http {
    upstream asset_nodes {
        server assets:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://asset_nodes;
        }
    }
}