events { worker_connections 1024; }
http {
    upstream website_nodes {
        server website:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://website_nodes;
            proxy_set_header Host $host;
        }
    }
}