events { worker_connections 1024; }

http {
    upstream api_cluster {
        server api:3000;
    }

    server {
        listen 80;

        # --- Rota 1: API (Backend) ---
        # Redireciona pedidos da API para o Node.js
        location ~ ^/(scan|scans|targets|health|presets) {
            proxy_pass http://api_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Websockets (Necessário para o Socket.io)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # --- Rota 2: Recursos (Pasta Resources) ---
        # Se pedires http://localhost/resources/CheckOut/...
        location /resources/ {
            # Remove a palavra '/resources/' do URL antes de passar ao contentor
            rewrite ^/resources/(.*) /$1 break;
            proxy_pass http://assets;
        }

        # --- Rota 3: Site Principal (Pasta VsCode) ---
        # Qualquer outra coisa abre o site HTML
        location / {
            proxy_pass http://website;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}